### PR TITLE
fail if ncurses.h is not found

### PR DESCRIPTION
**Pull request by LinuxMatt**
./configure script should fail if ncurses.h is not found.
It will tell the user that ncurses development package is probably not installed.
On Ubuntu 14.04,  _sudo apt-get install libncurses5-dev_ will install the requirement.

### CODE REVIEW

**Comment by lavv17** [comment]
_nct_ can be compiled with plain curses.h too (e.g. on Solaris). So it's necessary to check that neigher curses.h nor ncurses.h are available.

**Comment by LinuxMatt** [comment]
Would the 'AX_WITH_CURSES' macro work on Solaris ?
http://www.gnu.org/software/autoconf-archive/ax_with_curses.html

**Comment by lavv17** [comment]
Thanks for the hint! I have used that macro, please test 7ab2bd8

**Comment by LinuxMatt** [comment]
Hello,
On Ubuntu 14.04, autogen.sh does not work  anymore with your last commit that requires gnulib.
It also means that 47.2 megabytes of dependencies must be installed.
https://gist.github.com/LinuxMatt/bb69a88f6968554bf47e

Another patch :
https://github.com/LinuxMatt/nct/commit/88ecb5d45a2b531cf7a0e894cd05652fc93ffdce

**Comment by lavv17** [comment]
Maybe gnulib here is an overkill. Do we need that much portability?

**Comment by lavv17** [comment]
Can you please re-check HEAD, is it ok now?

2015-11-30 23:30 GMT+03:00 Matt Thirtytwo notifications@github.com:

> Hello,
> On Ubuntu 14.04, autogen.sh does not work anymore with your last commit
> that requires gnulib.
> It also means that 47.2 megabytes of dependencies must be installed.
> https://gist.github.com/LinuxMatt/bb69a88f6968554bf47e
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lavv17/nct/pull/1#issuecomment-160752687.

## 

   Alexander.

**Comment by LinuxMatt** [comment]
Still not working, choke on AC_CONFIG_AUX_DIR([build-aux]) 

https://gist.github.com/LinuxMatt/bb69a88f6968554bf47e

**Comment by LinuxMatt** [comment]
Hello,
You can check the build status on Travis CI (build machine is Ubuntu 12.04 LTS).
https://travis-ci.org/LinuxMatt/nct

Could you merge the .travis.yml file to your repo ?
See my commits:
https://github.com/LinuxMatt/nct/commit/facc3192a287af8ca020117612024d7247ad25f7
https://github.com/LinuxMatt/nct/commit/1455ffbefd87916b7b381f4ef7cae1823e8faf82

**Comment by lavv17** [comment]
Ok, finally it compiles on the travis-ci: https://travis-ci.org/lavv17/nct
I wonder if they have outdated auto-tools. My fedora 21 had no problems with creating build-aux and also autoreconf could include ax_with_curses automatically.

**Comment by LinuxMatt** [comment]
I works on Ubuntu 14.04 as well. Thank you.

**Pull request closed without merging**
